Add TheJobOverflow Problem Parser
jmerle/competitive-companion pull request #359
Opened 2023-06-06 16:10 UTC by touhidurrr

resolves #356 

I tested and it works.

2023-06-09 11:08 UTC, jmerle requested changes
Looking good, just two minor comments.

2023-06-09 11:08 UTC, jmerle commented on src/parsers/problem/TheJobOverflowProblemParser.ts
> +    for (let i = 0; i < inputs.length; i++) {
Similar to your other PR, the constraint, you use `outputs[i]` in the body so `i < inputs.length` should be `i < input.length && i < outputs.length`.

2023-06-09 11:10 UTC, jmerle commented on src/parsers/problem/TheJobOverflowProblemParser.ts
> +    return ['http://thejoboverflow.com/problem/*'];
TheJobOverflow also seems to support https, please include "https://thejoboverflow.com/problem/*" as well.

2023-06-10 11:05 UTC, jmerle requested changes
Sorry, I forgot to approve the GitHub Actions build yesterday, please run `pnpm fix` to fix code style issues and make the build pass. Other than that it looks good!

2023-06-10 11:39 UTC, jmerle approved these changes
LGTM :+1:

Will be released after #358 is merged.

2023-06-10 11:39 UTC, merged

2023-06-10 18:16 UTC, sagnikghoshcr7 commented
Still it is not working

2023-06-10 19:28 UTC, touhidurrr commented
> working

Wait for Chrome Web Store to show version 2.4.4

2023-06-11 07:50 UTC, touhidurrr commented
@jmerle how much time does it take for the extension update to be available on Chrome Web Store?

2023-06-12 17:45 UTC, touhidurrr commented
@sagnikghoshcr7 is it working now?

2023-06-12 19:01 UTC, sagnikghoshcr7 commented
Yes

2023-06-12 19:01 UTC, sagnikghoshcr7 commented
@touhidurrr Yes

2023-06-17 15:26 UTC, jmerle commented
> @jmerle how much time does it take for the extension update to be available on Chrome Web Store?

When I submit a new version to the Chrome Web Store it says it can take up to 30 days for it to be reviewed, but usually it happens within 24 hours. I don't know at what interval Chrome checks for extension updates, that probably adds another ~24 hours to the process of getting the latest version.